[package]
name = "the-rust-book-example"
version = "0.1.0"
edition = "2021"
author= "Yuhanna kapali <yuhannakapali@gamil.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
